apiVersion: v1
kind: Service
metadata:
  name: balance-service-store
  labels:
    app: balance-service
spec:
  ports:
  - port: 6379
  selector:
    app: balance-service
    tier: redis
  clusterIP: None
